### ISSUE TITLE
License for data re-use

### ISSUE THREAD

**Issue by DILewis** [devstronomy/nasa-data-scraper#1]
This is a really great resource, thank you. It'd be really helpful if you could add a license to this project – not just for the software, but for the data too.

**Comment by mkrauskopf** [comment]
Hi David. I've added the MIT license for the project. I'm not sure what do you mean by the license for the data. I want/consider everything, including data in the project to be "free for all" :), but not sure how to express this properly here, within the source code. Any idea, or patch? Thanks.

**Comment by DILewis** [comment]
That's really helpful, thank you. I had assumed your intention was to be as open as possible, but for the teaching materials I'd like to use it for, my editors would have needed some sort of license to allow me to use it. 
I'm not a lawyer, and I'd guess that MIT is probably fine for my needs, but it is a code license, so isn't necessarily as explicit as, for example, a Creative Commons license. I assume that the NASA data is public domain, so CC0 might be appropriate. I have no experience of mixed repos like this, so not sure how they'd interact... maybe safer to stick with MIT for now.

**Comment by mkrauskopf** [comment]
I'm (almost?) sure I've read in the past that NASA/JPL data, used in this project as a source, can be freely used as long as there is a pointer to the NASA data origin (which I've included). I'm not able to find it now.

I'm just translating data into different formats. But I'm not sure whether I can somehow license that. Also not a lawyer. I should probably invest more time here to make this clear.

I'm closing this issue for now. If you would have some hints regarding the licensing, please let me know. Thanks.
